package Login;

import java.sql.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author ISAAC HOREB
 */
public class Login extends javax.swing.JFrame {

    //Importamo la instancia
    Conexion instanciaMysql = Conexion.getInstancia();

    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    private void ValidarUsuario() {

        //Convertimos los punto a letras de la contraneña
        String password = String.valueOf(cajaPassworrd.getPassword());
        String usuario = cajaUsuarrio.getText().trim();

        //Condicional 
        if (password.equals("") || cajaUsuarrio.getText().equals("")) {
            mostrarMensajeErrorRegisrarUsuario();
        } else {

            try {
                boolean usuarioExiste = false;
                Connection conexionMysql = instanciaMysql.conectar();
                PreparedStatement seleccion = conexionMysql.prepareStatement("SELECT * FROM registro WHERE usuario ='" + usuario + "' AND contraseña ='" + password + "'");

                ResultSet consulta = seleccion.executeQuery();

                if (consulta.next()) {

                    usuarioExiste = true;

                    if (usuarioExiste == true) {

                        limpiar();
                        CRUD_Tienda crudTable = new CRUD_Tienda();
                        this.setVisible(false);
                        crudTable.setVisible(true);
                    }

                } else {
                    mostrarMensajeUsuarioNoEncontrado();
                }

                //instanciaMysql.cerrarConexion();
            } catch (SQLException e) {
                System.out.println(e);
            }

        }

    }

    private void RegistrarUsuario() {

        try {
            //Convertimos los punto a letras de la contraneña
            String password = String.valueOf(cajaPassworrd.getPassword());

            //Condicional 
            if (password.equals("") || cajaUsuarrio.getText().equals("")) {
                mostrarMensajeErrorRegisrarUsuario();
            } else {

                try {

                    Connection conexionMysql = instanciaMysql.conectar();
                    PreparedStatement insercion = conexionMysql.prepareStatement("INSERT INTO registro(usuario,contraseña) value (?,?)");

                    insercion.setString(1, cajaUsuarrio.getText().trim());
                    insercion.setString(2, password);
                    insercion.executeUpdate();

                    instanciaMysql.cerrarConexion();

                    mostrarMensajeValidarRegisrarUsuario();
                    limpiar();

                } catch (SQLException e) {
                    System.out.println(e);
                }

            }

        } catch (Exception e) {
            System.out.println(e);
        }

    }

    //Para agregar icono a una ventana emergente de error
    private void mostrarMensajeErrorRegisrarUsuario() {
        Icon icono = new ImageIcon(getClass().getResource("Error_Incorrecto.png"));
        JOptionPane.showMessageDialog(rootPane, "Error,verifique que sus datos sean correctos", "MENSAJE", JOptionPane.PLAIN_MESSAGE, icono);
    }

    //Para agregar icono a una ventana emergente de correcto
    private void mostrarMensajeValidarRegisrarUsuario() {
        Icon icono = new ImageIcon(getClass().getResource("registro.png"));
        JOptionPane.showMessageDialog(rootPane, "Correcto, ha sido verificado", "MENSAJE", JOptionPane.PLAIN_MESSAGE, icono);
    }

    //Para agregar icono a una ventana emergente de correcto
    private void mostrarMensajeUsuarioNoEncontrado() {
        Icon icono = new ImageIcon(getClass().getResource("Error_Incorrecto.png"));
        JOptionPane.showMessageDialog(rootPane, "¡Usuario no encontrado,verificado sus datos!", "MENSAJE", JOptionPane.PLAIN_MESSAGE, icono);
    }

    private void limpiar() {
        cajaPassworrd.setText("");
        cajaUsuarrio.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cajaUsuarrio = new javax.swing.JTextField();
        cajaPassworrd = new javax.swing.JPasswordField();
        btn_InicioSeccion = new javax.swing.JToggleButton();
        btn_Regiistar = new javax.swing.JToggleButton();
        btn_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setBackground(new java.awt.Color(0, 0, 204));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Iniciar Seccion");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/User.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario:");

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password:");

        cajaUsuarrio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cajaUsuarrio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaUsuarrioActionPerformed(evt);
            }
        });

        cajaPassworrd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_InicioSeccion.setBackground(new java.awt.Color(0, 51, 204));
        btn_InicioSeccion.setFont(new java.awt.Font("Gill Sans MT", 1, 15)); // NOI18N
        btn_InicioSeccion.setForeground(new java.awt.Color(255, 255, 255));
        btn_InicioSeccion.setText("Iniciar ");
        btn_InicioSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InicioSeccionActionPerformed(evt);
            }
        });

        btn_Regiistar.setBackground(new java.awt.Color(0, 51, 204));
        btn_Regiistar.setFont(new java.awt.Font("Gill Sans MT", 1, 15)); // NOI18N
        btn_Regiistar.setForeground(new java.awt.Color(255, 255, 255));
        btn_Regiistar.setText("Registrarse");
        btn_Regiistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegiistarActionPerformed(evt);
            }
        });

        btn_Salir.setBackground(new java.awt.Color(0, 51, 204));
        btn_Salir.setFont(new java.awt.Font("Gill Sans MT", 1, 15)); // NOI18N
        btn_Salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btn_InicioSeccion)
                                .addGap(35, 35, 35)
                                .addComponent(btn_Regiistar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cajaPassworrd))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(22, 22, 22)
                                .addComponent(cajaUsuarrio, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(83, 83, 83))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(cajaUsuarrio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cajaPassworrd, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(28, 28, 28)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Salir)
                    .addComponent(btn_Regiistar)
                    .addComponent(btn_InicioSeccion))
                .addGap(46, 46, 46))
        );

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_RegiistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegiistarActionPerformed
        RegistrarUsuario();
    }//GEN-LAST:event_btn_RegiistarActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        JOptionPane.showMessageDialog(null, "Programa Finalizado", "Mensaje", 1);
        System.exit(0);
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void btn_InicioSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InicioSeccionActionPerformed
        ValidarUsuario();
    }//GEN-LAST:event_btn_InicioSeccionActionPerformed

    private void cajaUsuarrioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaUsuarrioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajaUsuarrioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_InicioSeccion;
    private javax.swing.JToggleButton btn_Regiistar;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JPasswordField cajaPassworrd;
    private javax.swing.JTextField cajaUsuarrio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
